---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ramxx/cfjump-alpine
    tag: "v0.2"

inputs:
  - name: create-bosh-repo

run:
  path: create-bosh/ci/tasks/create-bosh-test.sh
