resources:
- name: create-bosh
  type: git
  source:
    branch: master
    uri: https://github.com/ECSTeam/create-bosh
    user: {{scripts-git-username}}
    password: {{scripts-git-password}}
    
jobs:
- name: create
  plan:
  - aggregate:
    - get: create-bosh
      trigger: true
  - task: create
    file: create-bosh/ci/tasks/create-bosh-test.yml
